### ISSUE TITLE
Bluetooth Audio stutters / shutters

### ISSUE THREAD

**Issue by not-a-doctor-stromberg** [PNDeb/pinenote-debian-image#20]
We are able to achieve stable bluetooth connections to devices like keyboards, but audio stutters a lot when trying to stream audio over bluetooth. I tried adding latency as described [here](https://wiki.pine64.org/wiki/PineNote_Development/TODOs#Trying_to_fix_bluetooth), but that didn't work. I noticed the best results with SBC codec.

**Comment by m-weigand** [comment]
the chat provided:

https://lore.kernel.org/linux-arm-kernel/20220926055435.31284-1-leo@nabam.net/T/

user hmpthcs reports: "(that is, on AAC..SBC seems ok, but SBC-XQ is still problematic. maybe slightly better than AAC was before)"

**Comment by m-weigand** [comment]
I think this was fixed by enabling dma for the BT UART. Fixed in the 6.9 branch of the Pinenote kernel
