### ISSUE TITLE
Better support for the backlight when the PN goes to sleep or is locked

### ISSUE THREAD

**Issue by not-a-doctor-stromberg** [PNDeb/pinenote-debian-image#26]
The backlight stays on when Debian goes to sleep or is locked. IMO, a decent default functionality would be:

**Locked** (after 15 minutes inactivity?)
1. Backlight remains on (dimmed?)
2. Backlight off after a minute with no input
3. Backlight comes back on if the device detects input (keypress / touch)
4. Suspend after 5 minutes

**Suspended** (when the hardware button is pressed)
1. Device locked if unlocked and screen is blanked (this already happens)
2. Backlight off

Some of this may already happen, but at least the backlight stuff doesn't turn off and I believe it should.

**Comment by m-weigand** [comment]
the lm3630a driver now turns off the backlight on suspend

https://github.com/m-weigand/linux/commit/c39c59b464d943b9ba9733a9bc54f81402a25cd7

**Comment by jonassmedegaard** [comment]
this issue seems solved.  Should it perhaps be closed, of if not clarified what is still pending?
