### ISSUE TITLE
Updating modified/pinned packages

### ISSUE THREAD

**Issue by m-weigand** [PNDeb/pinenote-debian-image#38]
Currently we do not have a nice way to update modified and pinned packages. We will track and discuss possible solutions in this issue.

**Comment by gled-rs** [comment]
I can host a debian repository if you want ? 

It is just a matter of setting it to a better priority than upstream. 

Let me know if you are interested !

**Comment by m-weigand** [comment]
@gled-rs Could you ping me in the matrix chat for further discussion regarding the repository, if the offer still stands? thanks!

**Comment by gled-rs** [comment]
> 

I need to reinstall my matrix server, some hardware issues but I will soon get the replacement gear and will ping you. 

yes offer still stands.

**Comment by m-weigand** [comment]
cool, thanks. I also found a short-term solution for initial testing, so no rush there.

**Comment by m-weigand** [comment]
closing this for now, the current approach works for now.
