### ISSUE TITLE
Latest release tries to boot from an incorrect partition

### ISSUE THREAD

**Issue by david-boles** [PNDeb/pinenote-debian-image#41]
Hello! It looks like (at least) the [latest release](https://github.com/m-weigand/pinenote-debian-recipes/releases/tag/v20230202) uses `/dev/mmcblk0p8` in `/boot/extlinux/extlinux.conf` instead of `/dev/mmcblk0p17`. I assume that isn't intentional?

I changed it myself and everything is working incredibly well! Huge thanks for this project!

**Comment by gled-rs** [comment]
With the partition table you should be using with the test images, it is correct.

if you did not use https://github.com/m-weigand/pinenote-debian-recipes/raw/dev/partition_tables/partition_table_standard1.txt then yeah you may have to adapt things.

**Comment by m-weigand** [comment]
It's a documentation thing... the documentation still uses partitoin 17 as we wanted to preserve android until things stabilized. With the new u-boot working without any android files we now want to switch to partition 8 for os1.

**Comment by m-weigand** [comment]
Closing this, as we are moving to a new partition layout, nonetheless.
