### ISSUE TITLE
Debian repository: missing URL of GPG key in README

### ISSUE THREAD

**Issue by aumouvantsillage** [PNDeb/pinenote-debian-image#44]
In section "PineNote-specific Debian repository", the following command is provided to download the public GPG key of the repository:

```
wget -o /etc/apt/keyrings/pinenote_repo_key_1.gpg URL
```

I assume that "URL" stands for the actual URL of the key, but I could not find which URL to use.
Is this information available somewhere in another document?

**Comment by anomaly256** [comment]
Came here to post the same thing.  If this key url is mentioned somewhere I'm not seeing it

**Comment by gled-rs** [comment]
it seems like the repo is not setup yet, the url of the repo does not contain any packages. @m-weigand is probably testing it.

**Comment by m-weigand** [comment]
should be fixed
