### ISSUE TITLE
image needlessly include libllvm14

### ISSUE THREAD

**Issue by jonassmedegaard** [PNDeb/pinenote-debian-image#48]
[Newest generated image](https://github.com/PNDeb/pinenote-debian-image/tree/v20230608_test1) includes package libllvm14 which is unused.  Package is 104 MB so not an insignificant waste of space, by some measures.

**Comment by jonassmedegaard** [comment]
Also include python3-numpy - unless used by some not-in-custom-package script of yours, that one is unused as well, and is 30 MB.

**Comment by m-weigand** [comment]
libllvm14 is not installed in the trixie image anymore
