### ISSUE TITLE
Updated brcm80211 firmware deb url

### ISSUE THREAD

**Issue by diederikdehaas** [PNDeb/pinenote-debian-image#51]
I made an update to my firmware repo which means https://github.com/PNDeb/pinenote-debian-image/blob/main/prep_03_custom_debs.sh#L64 now points to a no-longer-existing place.

The new URL is the following:
https://salsa.debian.org/diederik/firmware-nonfree/-/jobs/4652912/artifacts/file/debian/output/firmware-brcm80211_20230625-1+salsaci_all.deb

**Comment by m-weigand** [comment]
thanks, updated
